// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehzeftelmznvpxprbcda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoemVmdGVsbXpudnB4cHJiY2RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MTc2MjEsImV4cCI6MjA1ODk5MzYyMX0.JlWDd1T9Vgc-N-icvbR_Y1GPfcNkDifzoFvZdN4C41Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);